# Dockerfile.frontend

# ビルドステージ
FROM node:23.3.0 AS builder

WORKDIR /app

COPY ./frontend/package*.json ./
RUN npm install

COPY ./frontend .

RUN npm run build

# 実行ステージ
FROM node:23.3.0

WORKDIR /app

COPY --from=builder /app ./

EXPOSE 3000

CMD ["npm", "run", "start:prod"]