version: '3.9'

services:
  postgres:
    build:
      context: .
      dockerfile: docker/pgdb/Dockerfile
    container_name: pgdb
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    tmpfs:
      - /var/lib/postgresql/data

  envoy:
    image: envoyproxy/envoy:v1.31.0
    container_name: envoy
    volumes:
      - ./infra/envoy/envoy.dev.yaml:/etc/envoy/envoy.yaml
    ports:
      - "80:${ENVOY_PORT}"
    command: envoy -c /etc/envoy/envoy.yaml --log-level debug
