version: '3.9'

services:
  backend:
    volumes:
      - ./backend:/app
    working_dir: /app
    command: go run main.go
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    environment:
      - ENV=development
    depends_on:
      - postgres

  frontend:
    volumes:
      - ./frontend:/app
    working_dir: /app
    command: npm start
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    environment:
      - NODE_ENV=development
