version: '3.9'

services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile.pgdb
    container_name: pgdb
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"

  envoy:
    image: envoyproxy/envoy:v1.31.0
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
    ports:
      - "8080:${ENVOY_PORT}"
      - "9901:9901"
    command: envoy -c /etc/envoy/envoy.yaml --log-level debug
