version: '3.9'

services:
  postgres:
    build:
      context: .
      dockerfile: docker/pgdb/Dockerfile
    image: ghcr.io/asaycle/routiq-pgdb:latest
    container_name: pgdb
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"

  envoy:
    image: envoyproxy/envoy:v1.35-latest
    container_name: envoy
    ports:
      - "443:443"
    volumes:
      - ./docker/envoy/envoy.prod.yaml:/etc/envoy/envoy.yaml
      - /etc/letsencrypt/archive/routiq.jp:/etc/certs/routiq.jp:ro
      - /etc/letsencrypt/archive/api.routiq.jp:/etc/certs/api.routiq.jp:ro
    depends_on:
      - frontend
      - backend
    networks:
      - app-network

  frontend:
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
    image: ghcr.io/asaycle/routiq-frontend:latest
    container_name: frontend
    volumes:
      #- ./dist:/usr/share/nginx/html
      - ./docker/frontend/nginx.conf:/etc/nginx/conf.d/default.conf
    expose:
      - "80"
    networks:
      - app-network

  backend:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    image: ghcr.io/asaycle/routiq-backend:latest
    container_name: backend
    restart: always
    environment:
      - ENV=production
    expose:
      - "50051"
    networks:
      - app-network
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

networks:
  app-network:
    driver: bridge

