// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: v1/announcement.proto

package routiq

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// リソース本体（AIP-122）
type Announcement struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// リソース名: announcements/{announcement}
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// 表示用フィールド
	Title string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"` // 必須
	Body  string `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`   // 詳細説明（任意、マークダウン可）
	// メタ情報
	CreateTime    *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"` // AIP-142（*_time 命名）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Announcement) Reset() {
	*x = Announcement{}
	mi := &file_v1_announcement_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Announcement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Announcement) ProtoMessage() {}

func (x *Announcement) ProtoReflect() protoreflect.Message {
	mi := &file_v1_announcement_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Announcement.ProtoReflect.Descriptor instead.
func (*Announcement) Descriptor() ([]byte, []int) {
	return file_v1_announcement_proto_rawDescGZIP(), []int{0}
}

func (x *Announcement) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Announcement) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Announcement) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *Announcement) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

// AIP-132/160 に沿った一覧
type ListAnnouncementsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageSize      int32                  `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	Filter        string                 `protobuf:"bytes,3,opt,name=filter,proto3" json:"filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAnnouncementsRequest) Reset() {
	*x = ListAnnouncementsRequest{}
	mi := &file_v1_announcement_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAnnouncementsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAnnouncementsRequest) ProtoMessage() {}

func (x *ListAnnouncementsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_announcement_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAnnouncementsRequest.ProtoReflect.Descriptor instead.
func (*ListAnnouncementsRequest) Descriptor() ([]byte, []int) {
	return file_v1_announcement_proto_rawDescGZIP(), []int{1}
}

func (x *ListAnnouncementsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListAnnouncementsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListAnnouncementsRequest) GetFilter() string {
	if x != nil {
		return x.Filter
	}
	return ""
}

type ListAnnouncementsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Announcements []*Announcement        `protobuf:"bytes,1,rep,name=announcements,proto3" json:"announcements,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAnnouncementsResponse) Reset() {
	*x = ListAnnouncementsResponse{}
	mi := &file_v1_announcement_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAnnouncementsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAnnouncementsResponse) ProtoMessage() {}

func (x *ListAnnouncementsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_announcement_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAnnouncementsResponse.ProtoReflect.Descriptor instead.
func (*ListAnnouncementsResponse) Descriptor() ([]byte, []int) {
	return file_v1_announcement_proto_rawDescGZIP(), []int{2}
}

func (x *ListAnnouncementsResponse) GetAnnouncements() []*Announcement {
	if x != nil {
		return x.Announcements
	}
	return nil
}

func (x *ListAnnouncementsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

// 単体取得
type GetAnnouncementRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAnnouncementRequest) Reset() {
	*x = GetAnnouncementRequest{}
	mi := &file_v1_announcement_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAnnouncementRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAnnouncementRequest) ProtoMessage() {}

func (x *GetAnnouncementRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_announcement_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAnnouncementRequest.ProtoReflect.Descriptor instead.
func (*GetAnnouncementRequest) Descriptor() ([]byte, []int) {
	return file_v1_announcement_proto_rawDescGZIP(), []int{3}
}

func (x *GetAnnouncementRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_v1_announcement_proto protoreflect.FileDescriptor

const file_v1_announcement_proto_rawDesc = "" +
	"\n" +
	"\x15v1/announcement.proto\x12\x11asaycle.routiq.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x19google/api/resource.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xe9\x01\n" +
	"\fAnnouncement\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x12\n" +
	"\x04body\x18\x03 \x01(\tR\x04body\x12;\n" +
	"\vcreate_time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"createTime:^\xeaA[\n" +
	"\x1easaycle.routiq.v1.Announcement\x12\x1cannouncements/{announcement}*\rannouncements2\fannouncement\"n\n" +
	"\x18ListAnnouncementsRequest\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\x12\x16\n" +
	"\x06filter\x18\x03 \x01(\tR\x06filter\"\x8a\x01\n" +
	"\x19ListAnnouncementsResponse\x12E\n" +
	"\rannouncements\x18\x01 \x03(\v2\x1f.asaycle.routiq.v1.AnnouncementR\rannouncements\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"Q\n" +
	"\x16GetAnnouncementRequest\x127\n" +
	"\x04name\x18\x01 \x01(\tB#\xfaA \n" +
	"\x1easaycle.routiq.v1.AnnouncementR\x04name2\xa5\x02\n" +
	"\x13AnnouncementService\x12\x89\x01\n" +
	"\x11ListAnnouncements\x12+.asaycle.routiq.v1.ListAnnouncementsRequest\x1a,.asaycle.routiq.v1.ListAnnouncementsResponse\"\x19\x82\xd3\xe4\x93\x02\x13\x12\x11/v1/announcements\x12\x81\x01\n" +
	"\x0fGetAnnouncement\x12).asaycle.routiq.v1.GetAnnouncementRequest\x1a\x1f.asaycle.routiq.v1.Announcement\"\"\x82\xd3\xe4\x93\x02\x1c\x12\x1a/v1/{name=announcements/*}B/Z-github.com/asaycle/routiq/api/proto/v1;routiqb\x06proto3"

var (
	file_v1_announcement_proto_rawDescOnce sync.Once
	file_v1_announcement_proto_rawDescData []byte
)

func file_v1_announcement_proto_rawDescGZIP() []byte {
	file_v1_announcement_proto_rawDescOnce.Do(func() {
		file_v1_announcement_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_announcement_proto_rawDesc), len(file_v1_announcement_proto_rawDesc)))
	})
	return file_v1_announcement_proto_rawDescData
}

var file_v1_announcement_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_v1_announcement_proto_goTypes = []any{
	(*Announcement)(nil),              // 0: asaycle.routiq.v1.Announcement
	(*ListAnnouncementsRequest)(nil),  // 1: asaycle.routiq.v1.ListAnnouncementsRequest
	(*ListAnnouncementsResponse)(nil), // 2: asaycle.routiq.v1.ListAnnouncementsResponse
	(*GetAnnouncementRequest)(nil),    // 3: asaycle.routiq.v1.GetAnnouncementRequest
	(*timestamppb.Timestamp)(nil),     // 4: google.protobuf.Timestamp
}
var file_v1_announcement_proto_depIdxs = []int32{
	4, // 0: asaycle.routiq.v1.Announcement.create_time:type_name -> google.protobuf.Timestamp
	0, // 1: asaycle.routiq.v1.ListAnnouncementsResponse.announcements:type_name -> asaycle.routiq.v1.Announcement
	1, // 2: asaycle.routiq.v1.AnnouncementService.ListAnnouncements:input_type -> asaycle.routiq.v1.ListAnnouncementsRequest
	3, // 3: asaycle.routiq.v1.AnnouncementService.GetAnnouncement:input_type -> asaycle.routiq.v1.GetAnnouncementRequest
	2, // 4: asaycle.routiq.v1.AnnouncementService.ListAnnouncements:output_type -> asaycle.routiq.v1.ListAnnouncementsResponse
	0, // 5: asaycle.routiq.v1.AnnouncementService.GetAnnouncement:output_type -> asaycle.routiq.v1.Announcement
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_v1_announcement_proto_init() }
func file_v1_announcement_proto_init() {
	if File_v1_announcement_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_announcement_proto_rawDesc), len(file_v1_announcement_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_announcement_proto_goTypes,
		DependencyIndexes: file_v1_announcement_proto_depIdxs,
		MessageInfos:      file_v1_announcement_proto_msgTypes,
	}.Build()
	File_v1_announcement_proto = out.File
	file_v1_announcement_proto_goTypes = nil
	file_v1_announcement_proto_depIdxs = nil
}
