// Code generated by protoc-gen-go-resourcename; DO NOT EDIT.
package routiq

// Announcement patterns
type AnnouncementNameVariant int

const (
	AnnouncementNameVariant0 AnnouncementNameVariant = 0 // announcements/{announcement}
)

var _AnnouncementVariants = [][]_pattern{
	{_pattern{_seg{_segLit, "announcements"}, _seg{_segVar, "announcement"}}},
}

type AnnouncementName struct {
	Variant      AnnouncementNameVariant
	announcement string
}

func ParseAnnouncementName(name string) (AnnouncementName, error) {
	vars, which, err := _parseByVariants(name, _AnnouncementVariants)
	if err != nil {
		return AnnouncementName{}, err
	}
	out := AnnouncementName{Variant: AnnouncementNameVariant(which)}
	out.announcement = vars["announcement"]
	return out, nil
}

func FormatAnnouncementName(announcement string) string {
	return "announcements" + "/" + announcement
}

func (n AnnouncementName) GetAnnouncement() string { return n.announcement }
