// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: v1/location.proto

package routiq

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/fieldmaskpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Pref struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`                                  // "prefs/25"
	DisplayName   string                 `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"` // 例: "滋賀県"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pref) Reset() {
	*x = Pref{}
	mi := &file_v1_location_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pref) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pref) ProtoMessage() {}

func (x *Pref) ProtoReflect() protoreflect.Message {
	mi := &file_v1_location_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pref.ProtoReflect.Descriptor instead.
func (*Pref) Descriptor() ([]byte, []int) {
	return file_v1_location_proto_rawDescGZIP(), []int{0}
}

func (x *Pref) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Pref) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

type City struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Name        string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`                                  // "prefs/25/cities/25201"
	DisplayName string                 `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"` // 例: "大津市"
	// Pref への参照
	Pref          string `protobuf:"bytes,3,opt,name=pref,proto3" json:"pref,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *City) Reset() {
	*x = City{}
	mi := &file_v1_location_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *City) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*City) ProtoMessage() {}

func (x *City) ProtoReflect() protoreflect.Message {
	mi := &file_v1_location_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use City.ProtoReflect.Descriptor instead.
func (*City) Descriptor() ([]byte, []int) {
	return file_v1_location_proto_rawDescGZIP(), []int{1}
}

func (x *City) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *City) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *City) GetPref() string {
	if x != nil {
		return x.Pref
	}
	return ""
}

type Location struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Name      string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`                            // "locations/{location}"
	UserLabel string                 `protobuf:"bytes,2,opt,name=user_label,json=userLabel,proto3" json:"user_label,omitempty"` // ユーザーが付けた表示名
	PlaceId   string                 `protobuf:"bytes,3,opt,name=place_id,json=placeId,proto3" json:"place_id,omitempty"`       // Google Place ID
	Lat       float64                `protobuf:"fixed64,4,opt,name=lat,proto3" json:"lat,omitempty"`
	Lng       float64                `protobuf:"fixed64,5,opt,name=lng,proto3" json:"lng,omitempty"`
	// Pref/City リソース参照
	Pref string `protobuf:"bytes,6,opt,name=pref,proto3" json:"pref,omitempty"`
	City string `protobuf:"bytes,7,opt,name=city,proto3" json:"city,omitempty"`
	// 正規化済みラベル（サーバ管理）
	UserLabelNorm string `protobuf:"bytes,8,opt,name=user_label_norm,json=userLabelNorm,proto3" json:"user_label_norm,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Location) Reset() {
	*x = Location{}
	mi := &file_v1_location_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Location) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Location) ProtoMessage() {}

func (x *Location) ProtoReflect() protoreflect.Message {
	mi := &file_v1_location_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Location.ProtoReflect.Descriptor instead.
func (*Location) Descriptor() ([]byte, []int) {
	return file_v1_location_proto_rawDescGZIP(), []int{2}
}

func (x *Location) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Location) GetUserLabel() string {
	if x != nil {
		return x.UserLabel
	}
	return ""
}

func (x *Location) GetPlaceId() string {
	if x != nil {
		return x.PlaceId
	}
	return ""
}

func (x *Location) GetLat() float64 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *Location) GetLng() float64 {
	if x != nil {
		return x.Lng
	}
	return 0
}

func (x *Location) GetPref() string {
	if x != nil {
		return x.Pref
	}
	return ""
}

func (x *Location) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *Location) GetUserLabelNorm() string {
	if x != nil {
		return x.UserLabelNorm
	}
	return ""
}

type ListPrefsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageSize      int32                  `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`   // 1ページあたりの結果数
	PageToken     string                 `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"` // 次のページへのトークン
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPrefsRequest) Reset() {
	*x = ListPrefsRequest{}
	mi := &file_v1_location_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPrefsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPrefsRequest) ProtoMessage() {}

func (x *ListPrefsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_location_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPrefsRequest.ProtoReflect.Descriptor instead.
func (*ListPrefsRequest) Descriptor() ([]byte, []int) {
	return file_v1_location_proto_rawDescGZIP(), []int{3}
}

func (x *ListPrefsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListPrefsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListPrefsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"` // 次のページへのトークン
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPrefsResponse) Reset() {
	*x = ListPrefsResponse{}
	mi := &file_v1_location_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPrefsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPrefsResponse) ProtoMessage() {}

func (x *ListPrefsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_location_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPrefsResponse.ProtoReflect.Descriptor instead.
func (*ListPrefsResponse) Descriptor() ([]byte, []int) {
	return file_v1_location_proto_rawDescGZIP(), []int{4}
}

func (x *ListPrefsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type GetPrefRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"` // "prefs/25"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPrefRequest) Reset() {
	*x = GetPrefRequest{}
	mi := &file_v1_location_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPrefRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPrefRequest) ProtoMessage() {}

func (x *GetPrefRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_location_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPrefRequest.ProtoReflect.Descriptor instead.
func (*GetPrefRequest) Descriptor() ([]byte, []int) {
	return file_v1_location_proto_rawDescGZIP(), []int{5}
}

func (x *GetPrefRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ListCitiesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filter        string                 `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`                        // "prefs/25"
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`   // 1ページあたりの結果数
	PageToken     string                 `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"` // 次のページへのトークン
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCitiesRequest) Reset() {
	*x = ListCitiesRequest{}
	mi := &file_v1_location_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCitiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCitiesRequest) ProtoMessage() {}

func (x *ListCitiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_location_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCitiesRequest.ProtoReflect.Descriptor instead.
func (*ListCitiesRequest) Descriptor() ([]byte, []int) {
	return file_v1_location_proto_rawDescGZIP(), []int{6}
}

func (x *ListCitiesRequest) GetFilter() string {
	if x != nil {
		return x.Filter
	}
	return ""
}

func (x *ListCitiesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListCitiesRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListCitiesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cities        []*City                `protobuf:"bytes,1,rep,name=cities,proto3" json:"cities,omitempty"`                                      // 一覧の都市
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"` // 次のページへのトークン
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCitiesResponse) Reset() {
	*x = ListCitiesResponse{}
	mi := &file_v1_location_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCitiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCitiesResponse) ProtoMessage() {}

func (x *ListCitiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_location_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCitiesResponse.ProtoReflect.Descriptor instead.
func (*ListCitiesResponse) Descriptor() ([]byte, []int) {
	return file_v1_location_proto_rawDescGZIP(), []int{7}
}

func (x *ListCitiesResponse) GetCities() []*City {
	if x != nil {
		return x.Cities
	}
	return nil
}

func (x *ListCitiesResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type GetCityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"` // "prefs/25/cities/25201"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCityRequest) Reset() {
	*x = GetCityRequest{}
	mi := &file_v1_location_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCityRequest) ProtoMessage() {}

func (x *GetCityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_location_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCityRequest.ProtoReflect.Descriptor instead.
func (*GetCityRequest) Descriptor() ([]byte, []int) {
	return file_v1_location_proto_rawDescGZIP(), []int{8}
}

func (x *GetCityRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_v1_location_proto protoreflect.FileDescriptor

const file_v1_location_proto_rawDesc = "" +
	"\n" +
	"\x11v1/location.proto\x12\x11asaycle.routiq.v1\x1a\x19google/api/resource.proto\x1a\x1cgoogle/api/annotations.proto\x1a google/protobuf/field_mask.proto\"u\n" +
	"\x04Pref\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName:6\xeaA3\n" +
	"\x16asaycle.routiq.v1.Pref\x12\fprefs/{pref}*\x05prefs2\x04pref\"\xb5\x01\n" +
	"\x04City\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x12/\n" +
	"\x04pref\x18\x03 \x01(\tB\x1b\xfaA\x18\n" +
	"\x16asaycle.routiq.v1.PrefR\x04pref:E\xeaAB\n" +
	"\x16asaycle.routiq.v1.City\x12\x1aprefs/{pref}/cities/{city}*\x06cities2\x04city\"\xd2\x02\n" +
	"\bLocation\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"user_label\x18\x02 \x01(\tR\tuserLabel\x12\x19\n" +
	"\bplace_id\x18\x03 \x01(\tR\aplaceId\x12\x10\n" +
	"\x03lat\x18\x04 \x01(\x01R\x03lat\x12\x10\n" +
	"\x03lng\x18\x05 \x01(\x01R\x03lng\x12/\n" +
	"\x04pref\x18\x06 \x01(\tB\x1b\xfaA\x18\n" +
	"\x16asaycle.routiq.v1.PrefR\x04pref\x12/\n" +
	"\x04city\x18\a \x01(\tB\x1b\xfaA\x18\n" +
	"\x16asaycle.routiq.v1.CityR\x04city\x12&\n" +
	"\x0fuser_label_norm\x18\b \x01(\tR\ruserLabelNorm:J\xeaAG\n" +
	"\x1aasaycle.routiq.v1.Location\x12\x14locations/{location}*\tlocations2\blocation\"N\n" +
	"\x10ListPrefsRequest\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\";\n" +
	"\x11ListPrefsResponse\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"$\n" +
	"\x0eGetPrefRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"g\n" +
	"\x11ListCitiesRequest\x12\x16\n" +
	"\x06filter\x18\x01 \x01(\tR\x06filter\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x03 \x01(\tR\tpageToken\"m\n" +
	"\x12ListCitiesResponse\x12/\n" +
	"\x06cities\x18\x01 \x03(\v2\x17.asaycle.routiq.v1.CityR\x06cities\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"$\n" +
	"\x0eGetCityRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name2\xd2\x02\n" +
	"\x0fLocationService\x12V\n" +
	"\tListPrefs\x12#.asaycle.routiq.v1.ListPrefsRequest\x1a$.asaycle.routiq.v1.ListPrefsResponse\x12E\n" +
	"\aGetPref\x12!.asaycle.routiq.v1.GetPrefRequest\x1a\x17.asaycle.routiq.v1.Pref\x12Y\n" +
	"\n" +
	"ListCities\x12$.asaycle.routiq.v1.ListCitiesRequest\x1a%.asaycle.routiq.v1.ListCitiesResponse\x12E\n" +
	"\aGetCity\x12!.asaycle.routiq.v1.GetCityRequest\x1a\x17.asaycle.routiq.v1.CityB/Z-github.com/asaycle/routiq/api/proto/v1;routiqb\x06proto3"

var (
	file_v1_location_proto_rawDescOnce sync.Once
	file_v1_location_proto_rawDescData []byte
)

func file_v1_location_proto_rawDescGZIP() []byte {
	file_v1_location_proto_rawDescOnce.Do(func() {
		file_v1_location_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_location_proto_rawDesc), len(file_v1_location_proto_rawDesc)))
	})
	return file_v1_location_proto_rawDescData
}

var file_v1_location_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_v1_location_proto_goTypes = []any{
	(*Pref)(nil),               // 0: asaycle.routiq.v1.Pref
	(*City)(nil),               // 1: asaycle.routiq.v1.City
	(*Location)(nil),           // 2: asaycle.routiq.v1.Location
	(*ListPrefsRequest)(nil),   // 3: asaycle.routiq.v1.ListPrefsRequest
	(*ListPrefsResponse)(nil),  // 4: asaycle.routiq.v1.ListPrefsResponse
	(*GetPrefRequest)(nil),     // 5: asaycle.routiq.v1.GetPrefRequest
	(*ListCitiesRequest)(nil),  // 6: asaycle.routiq.v1.ListCitiesRequest
	(*ListCitiesResponse)(nil), // 7: asaycle.routiq.v1.ListCitiesResponse
	(*GetCityRequest)(nil),     // 8: asaycle.routiq.v1.GetCityRequest
}
var file_v1_location_proto_depIdxs = []int32{
	1, // 0: asaycle.routiq.v1.ListCitiesResponse.cities:type_name -> asaycle.routiq.v1.City
	3, // 1: asaycle.routiq.v1.LocationService.ListPrefs:input_type -> asaycle.routiq.v1.ListPrefsRequest
	5, // 2: asaycle.routiq.v1.LocationService.GetPref:input_type -> asaycle.routiq.v1.GetPrefRequest
	6, // 3: asaycle.routiq.v1.LocationService.ListCities:input_type -> asaycle.routiq.v1.ListCitiesRequest
	8, // 4: asaycle.routiq.v1.LocationService.GetCity:input_type -> asaycle.routiq.v1.GetCityRequest
	4, // 5: asaycle.routiq.v1.LocationService.ListPrefs:output_type -> asaycle.routiq.v1.ListPrefsResponse
	0, // 6: asaycle.routiq.v1.LocationService.GetPref:output_type -> asaycle.routiq.v1.Pref
	7, // 7: asaycle.routiq.v1.LocationService.ListCities:output_type -> asaycle.routiq.v1.ListCitiesResponse
	1, // 8: asaycle.routiq.v1.LocationService.GetCity:output_type -> asaycle.routiq.v1.City
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_v1_location_proto_init() }
func file_v1_location_proto_init() {
	if File_v1_location_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_location_proto_rawDesc), len(file_v1_location_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_location_proto_goTypes,
		DependencyIndexes: file_v1_location_proto_depIdxs,
		MessageInfos:      file_v1_location_proto_msgTypes,
	}.Build()
	File_v1_location_proto = out.File
	file_v1_location_proto_goTypes = nil
	file_v1_location_proto_depIdxs = nil
}
