// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: v1/pref.proto

package routiq

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListPrefsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageSize      int32                  `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`   // 1ページあたりの結果数
	PageToken     string                 `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"` // 次のページへのトークン
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPrefsRequest) Reset() {
	*x = ListPrefsRequest{}
	mi := &file_v1_pref_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPrefsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPrefsRequest) ProtoMessage() {}

func (x *ListPrefsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_pref_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPrefsRequest.ProtoReflect.Descriptor instead.
func (*ListPrefsRequest) Descriptor() ([]byte, []int) {
	return file_v1_pref_proto_rawDescGZIP(), []int{0}
}

func (x *ListPrefsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListPrefsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListPrefsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"` // 次のページへのトークン
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPrefsResponse) Reset() {
	*x = ListPrefsResponse{}
	mi := &file_v1_pref_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPrefsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPrefsResponse) ProtoMessage() {}

func (x *ListPrefsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_pref_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPrefsResponse.ProtoReflect.Descriptor instead.
func (*ListPrefsResponse) Descriptor() ([]byte, []int) {
	return file_v1_pref_proto_rawDescGZIP(), []int{1}
}

func (x *ListPrefsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

var File_v1_pref_proto protoreflect.FileDescriptor

const file_v1_pref_proto_rawDesc = "" +
	"\n" +
	"\rv1/pref.proto\x12\x11asaycle.routiq.v1\"N\n" +
	"\x10ListPrefsRequest\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\";\n" +
	"\x11ListPrefsResponse\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken2e\n" +
	"\vPrefService\x12V\n" +
	"\tListPrefs\x12#.asaycle.routiq.v1.ListPrefsRequest\x1a$.asaycle.routiq.v1.ListPrefsResponseB/Z-github.com/asaycle/routiq/api/proto/v1;routiqb\x06proto3"

var (
	file_v1_pref_proto_rawDescOnce sync.Once
	file_v1_pref_proto_rawDescData []byte
)

func file_v1_pref_proto_rawDescGZIP() []byte {
	file_v1_pref_proto_rawDescOnce.Do(func() {
		file_v1_pref_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_pref_proto_rawDesc), len(file_v1_pref_proto_rawDesc)))
	})
	return file_v1_pref_proto_rawDescData
}

var file_v1_pref_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_v1_pref_proto_goTypes = []any{
	(*ListPrefsRequest)(nil),  // 0: asaycle.routiq.v1.ListPrefsRequest
	(*ListPrefsResponse)(nil), // 1: asaycle.routiq.v1.ListPrefsResponse
}
var file_v1_pref_proto_depIdxs = []int32{
	0, // 0: asaycle.routiq.v1.PrefService.ListPrefs:input_type -> asaycle.routiq.v1.ListPrefsRequest
	1, // 1: asaycle.routiq.v1.PrefService.ListPrefs:output_type -> asaycle.routiq.v1.ListPrefsResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_v1_pref_proto_init() }
func file_v1_pref_proto_init() {
	if File_v1_pref_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_pref_proto_rawDesc), len(file_v1_pref_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_pref_proto_goTypes,
		DependencyIndexes: file_v1_pref_proto_depIdxs,
		MessageInfos:      file_v1_pref_proto_msgTypes,
	}.Build()
	File_v1_pref_proto = out.File
	file_v1_pref_proto_goTypes = nil
	file_v1_pref_proto_depIdxs = nil
}
