// Code generated by protoc-gen-go-resourcename; DO NOT EDIT.
package routiq

// Route patterns
type RouteNameVariant int

const (
	RouteNameVariant0 RouteNameVariant = 0 // routes/{route}
)

var _RouteVariants = [][]_pattern{
	{_pattern{_seg{_segLit, "routes"}, _seg{_segVar, "route"}}},
}

type RouteName struct {
	Variant RouteNameVariant
	route   string
}

func ParseRouteName(name string) (RouteName, error) {
	vars, which, err := _parseByVariants(name, _RouteVariants)
	if err != nil {
		return RouteName{}, err
	}
	out := RouteName{Variant: RouteNameVariant(which)}
	out.route = vars["route"]
	return out, nil
}

func FormatRouteName(route string) string {
	return "routes" + "/" + route
}

func (n RouteName) GetRoute() string { return n.route }
