// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: v1/tag.proto

package routiq

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Tag struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`                                  // format: tags/{tag}
	DisplayName   string                 `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"` // 表示用の名前
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tag) Reset() {
	*x = Tag{}
	mi := &file_v1_tag_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tag) ProtoMessage() {}

func (x *Tag) ProtoReflect() protoreflect.Message {
	mi := &file_v1_tag_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tag.ProtoReflect.Descriptor instead.
func (*Tag) Descriptor() ([]byte, []int) {
	return file_v1_tag_proto_rawDescGZIP(), []int{0}
}

func (x *Tag) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Tag) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

// タグ作成リクエスト
type CreateTagRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tag           *Tag                   `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag,omitempty"` // 作成するタグ
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTagRequest) Reset() {
	*x = CreateTagRequest{}
	mi := &file_v1_tag_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTagRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTagRequest) ProtoMessage() {}

func (x *CreateTagRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_tag_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTagRequest.ProtoReflect.Descriptor instead.
func (*CreateTagRequest) Descriptor() ([]byte, []int) {
	return file_v1_tag_proto_rawDescGZIP(), []int{1}
}

func (x *CreateTagRequest) GetTag() *Tag {
	if x != nil {
		return x.Tag
	}
	return nil
}

type ListTagsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filter        string                 `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`   // 1ページあたりの結果数
	PageToken     string                 `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"` // 次のページへのトークン
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTagsRequest) Reset() {
	*x = ListTagsRequest{}
	mi := &file_v1_tag_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTagsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTagsRequest) ProtoMessage() {}

func (x *ListTagsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_tag_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTagsRequest.ProtoReflect.Descriptor instead.
func (*ListTagsRequest) Descriptor() ([]byte, []int) {
	return file_v1_tag_proto_rawDescGZIP(), []int{2}
}

func (x *ListTagsRequest) GetFilter() string {
	if x != nil {
		return x.Filter
	}
	return ""
}

func (x *ListTagsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListTagsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListTagsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tags          []*Tag                 `protobuf:"bytes,1,rep,name=tags,proto3" json:"tags,omitempty"`                                          // Tagのリスト
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"` // 次のページへのトークン
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTagsResponse) Reset() {
	*x = ListTagsResponse{}
	mi := &file_v1_tag_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTagsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTagsResponse) ProtoMessage() {}

func (x *ListTagsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_tag_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTagsResponse.ProtoReflect.Descriptor instead.
func (*ListTagsResponse) Descriptor() ([]byte, []int) {
	return file_v1_tag_proto_rawDescGZIP(), []int{3}
}

func (x *ListTagsResponse) GetTags() []*Tag {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *ListTagsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

var File_v1_tag_proto protoreflect.FileDescriptor

const file_v1_tag_proto_rawDesc = "" +
	"\n" +
	"\fv1/tag.proto\x12\x11asaycle.routiq.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x19google/api/resource.proto\"o\n" +
	"\x03Tag\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName:1\xeaA.\n" +
	"\x15asaycle.routiq.v1.Tag\x12\n" +
	"tags/{tag}*\x04tags2\x03tag\"<\n" +
	"\x10CreateTagRequest\x12(\n" +
	"\x03tag\x18\x01 \x01(\v2\x16.asaycle.routiq.v1.TagR\x03tag\"e\n" +
	"\x0fListTagsRequest\x12\x16\n" +
	"\x06filter\x18\x01 \x01(\tR\x06filter\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x03 \x01(\tR\tpageToken\"f\n" +
	"\x10ListTagsResponse\x12*\n" +
	"\x04tags\x18\x01 \x03(\v2\x16.asaycle.routiq.v1.TagR\x04tags\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken2\x82\x02\n" +
	"\n" +
	"TagService\x12_\n" +
	"\tCreateTag\x12#.asaycle.routiq.v1.CreateTagRequest\x1a\x16.asaycle.routiq.v1.Tag\"\x15\x82\xd3\xe4\x93\x02\x0f:\x03tag\"\b/v1/tags\x12\x92\x01\n" +
	"\bListTags\x12\".asaycle.routiq.v1.ListTagsRequest\x1a#.asaycle.routiq.v1.ListTagsResponse\"=\x82\xd3\xe4\x93\x027Z+:\x01*\"&/asaycle.routiq.v1.TagService/ListTags\x12\b/v1/tagsB/Z-github.com/asaycle/routiq/api/proto/v1;routiqb\x06proto3"

var (
	file_v1_tag_proto_rawDescOnce sync.Once
	file_v1_tag_proto_rawDescData []byte
)

func file_v1_tag_proto_rawDescGZIP() []byte {
	file_v1_tag_proto_rawDescOnce.Do(func() {
		file_v1_tag_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_tag_proto_rawDesc), len(file_v1_tag_proto_rawDesc)))
	})
	return file_v1_tag_proto_rawDescData
}

var file_v1_tag_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_v1_tag_proto_goTypes = []any{
	(*Tag)(nil),              // 0: asaycle.routiq.v1.Tag
	(*CreateTagRequest)(nil), // 1: asaycle.routiq.v1.CreateTagRequest
	(*ListTagsRequest)(nil),  // 2: asaycle.routiq.v1.ListTagsRequest
	(*ListTagsResponse)(nil), // 3: asaycle.routiq.v1.ListTagsResponse
}
var file_v1_tag_proto_depIdxs = []int32{
	0, // 0: asaycle.routiq.v1.CreateTagRequest.tag:type_name -> asaycle.routiq.v1.Tag
	0, // 1: asaycle.routiq.v1.ListTagsResponse.tags:type_name -> asaycle.routiq.v1.Tag
	1, // 2: asaycle.routiq.v1.TagService.CreateTag:input_type -> asaycle.routiq.v1.CreateTagRequest
	2, // 3: asaycle.routiq.v1.TagService.ListTags:input_type -> asaycle.routiq.v1.ListTagsRequest
	0, // 4: asaycle.routiq.v1.TagService.CreateTag:output_type -> asaycle.routiq.v1.Tag
	3, // 5: asaycle.routiq.v1.TagService.ListTags:output_type -> asaycle.routiq.v1.ListTagsResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_v1_tag_proto_init() }
func file_v1_tag_proto_init() {
	if File_v1_tag_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_tag_proto_rawDesc), len(file_v1_tag_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_tag_proto_goTypes,
		DependencyIndexes: file_v1_tag_proto_depIdxs,
		MessageInfos:      file_v1_tag_proto_msgTypes,
	}.Build()
	File_v1_tag_proto = out.File
	file_v1_tag_proto_goTypes = nil
	file_v1_tag_proto_depIdxs = nil
}
