// Code generated by protoc-gen-go-resourcename; DO NOT EDIT.
package routiq

// Tag patterns
type TagNameVariant int

const (
	TagNameVariant0 TagNameVariant = 0 // tags/{tag}
)

var _TagVariants = [][]_pattern{
	{_pattern{_seg{_segLit, "tags"}, _seg{_segVar, "tag"}}},
}

type TagName struct {
	Variant TagNameVariant
	tag     string
}

func ParseTagName(name string) (TagName, error) {
	vars, which, err := _parseByVariants(name, _TagVariants)
	if err != nil {
		return TagName{}, err
	}
	out := TagName{Variant: TagNameVariant(which)}
	out.tag = vars["tag"]
	return out, nil
}

func FormatTagName(tag string) string {
	return "tags" + "/" + tag
}

func (n TagName) GetTag() string { return n.tag }
