// Code generated by protoc-gen-go-resourcename; DO NOT EDIT.
package routiq

// Touring patterns
type TouringNameVariant int

const (
	TouringNameVariant0 TouringNameVariant = 0 // routes/{route}/tourings/{touring}
)

var _TouringVariants = [][]_pattern{
	{_pattern{_seg{_segLit, "routes"}, _seg{_segVar, "route"}, _seg{_segLit, "tourings"}, _seg{_segVar, "touring"}}},
}

type TouringName struct {
	Variant TouringNameVariant
	route   string
	touring string
}

func ParseTouringName(name string) (TouringName, error) {
	vars, which, err := _parseByVariants(name, _TouringVariants)
	if err != nil {
		return TouringName{}, err
	}
	out := TouringName{Variant: TouringNameVariant(which)}
	out.route = vars["route"]
	out.touring = vars["touring"]
	return out, nil
}

func FormatTouringName(route string, touring string) string {
	return "routes" + "/" + route + "/" + "tourings" + "/" + touring
}

func (n TouringName) GetRoute() string { return n.route }

func (n TouringName) GetTouring() string { return n.touring }
