// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: v1/touring.proto

package routiq

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	date "google.golang.org/genproto/googleapis/type/date"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TouringView int32

const (
	TouringView_TOURING_VIEW_UNSPECIFIED TouringView = 0
	TouringView_TOURING_VIEW_BASIC       TouringView = 1 // tags は参照名のみ
	TouringView_TOURING_VIEW_WITH_TAGS   TouringView = 2 // 展開して詳細も同梱
)

// Enum value maps for TouringView.
var (
	TouringView_name = map[int32]string{
		0: "TOURING_VIEW_UNSPECIFIED",
		1: "TOURING_VIEW_BASIC",
		2: "TOURING_VIEW_WITH_TAGS",
	}
	TouringView_value = map[string]int32{
		"TOURING_VIEW_UNSPECIFIED": 0,
		"TOURING_VIEW_BASIC":       1,
		"TOURING_VIEW_WITH_TAGS":   2,
	}
)

func (x TouringView) Enum() *TouringView {
	p := new(TouringView)
	*p = x
	return p
}

func (x TouringView) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TouringView) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_touring_proto_enumTypes[0].Descriptor()
}

func (TouringView) Type() protoreflect.EnumType {
	return &file_v1_touring_proto_enumTypes[0]
}

func (x TouringView) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TouringView.Descriptor instead.
func (TouringView) EnumDescriptor() ([]byte, []int) {
	return file_v1_touring_proto_rawDescGZIP(), []int{0}
}

// Touring リソース定義
type Touring struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Route         string                 `protobuf:"bytes,2,opt,name=route,proto3" json:"route,omitempty"`
	Tags          []string               `protobuf:"bytes,3,rep,name=tags,proto3" json:"tags,omitempty"` // 例: ["tags/scape","tags/winding"]
	Date          *date.Date             `protobuf:"bytes,4,opt,name=date,proto3" json:"date,omitempty"`
	DisplayName   string                 `protobuf:"bytes,5,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"` // ルート名
	Note          string                 `protobuf:"bytes,6,opt,name=note,proto3" json:"note,omitempty"`
	Score         int32                  `protobuf:"varint,7,opt,name=score,proto3" json:"score,omitempty"`
	UserId        string                 `protobuf:"bytes,8,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CreateTime    *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`  // 作成日時 (ISO8601形式の文字列)
	UpdateTime    *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"` // 更新日時(ISO8601形式の文字列)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Touring) Reset() {
	*x = Touring{}
	mi := &file_v1_touring_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Touring) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Touring) ProtoMessage() {}

func (x *Touring) ProtoReflect() protoreflect.Message {
	mi := &file_v1_touring_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Touring.ProtoReflect.Descriptor instead.
func (*Touring) Descriptor() ([]byte, []int) {
	return file_v1_touring_proto_rawDescGZIP(), []int{0}
}

func (x *Touring) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Touring) GetRoute() string {
	if x != nil {
		return x.Route
	}
	return ""
}

func (x *Touring) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Touring) GetDate() *date.Date {
	if x != nil {
		return x.Date
	}
	return nil
}

func (x *Touring) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *Touring) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

func (x *Touring) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *Touring) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Touring) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

func (x *Touring) GetUpdateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdateTime
	}
	return nil
}

// CreateTouring RPC
type CreateTouringRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 親リソース: ツーリングが所属するルート
	// 例: "routes/1234567890abcdef"
	Parent        string   `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	Touring       *Touring `protobuf:"bytes,2,opt,name=touring,proto3" json:"touring,omitempty"` // 作成するツーリングの情報
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTouringRequest) Reset() {
	*x = CreateTouringRequest{}
	mi := &file_v1_touring_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTouringRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTouringRequest) ProtoMessage() {}

func (x *CreateTouringRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_touring_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTouringRequest.ProtoReflect.Descriptor instead.
func (*CreateTouringRequest) Descriptor() ([]byte, []int) {
	return file_v1_touring_proto_rawDescGZIP(), []int{1}
}

func (x *CreateTouringRequest) GetParent() string {
	if x != nil {
		return x.Parent
	}
	return ""
}

func (x *CreateTouringRequest) GetTouring() *Touring {
	if x != nil {
		return x.Touring
	}
	return nil
}

// ListTourings RPC
type ListTouringsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filter        string                 `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`            // 一度に取得するルートの数
	PageToken     string                 `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`          // 次のページを指定するトークン
	View          TouringView            `protobuf:"varint,4,opt,name=view,proto3,enum=asaycle.routiq.v1.TouringView" json:"view,omitempty"` // 取得するビューの種類
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTouringsRequest) Reset() {
	*x = ListTouringsRequest{}
	mi := &file_v1_touring_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTouringsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTouringsRequest) ProtoMessage() {}

func (x *ListTouringsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_touring_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTouringsRequest.ProtoReflect.Descriptor instead.
func (*ListTouringsRequest) Descriptor() ([]byte, []int) {
	return file_v1_touring_proto_rawDescGZIP(), []int{2}
}

func (x *ListTouringsRequest) GetFilter() string {
	if x != nil {
		return x.Filter
	}
	return ""
}

func (x *ListTouringsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListTouringsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListTouringsRequest) GetView() TouringView {
	if x != nil {
		return x.View
	}
	return TouringView_TOURING_VIEW_UNSPECIFIED
}

type ListTouringsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tourings      []*Touring             `protobuf:"bytes,1,rep,name=tourings,proto3" json:"tourings,omitempty"`
	IncludedTags  map[string]*Tag        `protobuf:"bytes,2,rep,name=included_tags,json=includedTags,proto3" json:"included_tags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	NextPageToken string                 `protobuf:"bytes,3,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"` // 次のページのトークン
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTouringsResponse) Reset() {
	*x = ListTouringsResponse{}
	mi := &file_v1_touring_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTouringsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTouringsResponse) ProtoMessage() {}

func (x *ListTouringsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_touring_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTouringsResponse.ProtoReflect.Descriptor instead.
func (*ListTouringsResponse) Descriptor() ([]byte, []int) {
	return file_v1_touring_proto_rawDescGZIP(), []int{3}
}

func (x *ListTouringsResponse) GetTourings() []*Touring {
	if x != nil {
		return x.Tourings
	}
	return nil
}

func (x *ListTouringsResponse) GetIncludedTags() map[string]*Tag {
	if x != nil {
		return x.IncludedTags
	}
	return nil
}

func (x *ListTouringsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

// GetTouring RPC
type GetTouringRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"` // 取得するルートのID
	View          TouringView            `protobuf:"varint,2,opt,name=view,proto3,enum=asaycle.routiq.v1.TouringView" json:"view,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTouringRequest) Reset() {
	*x = GetTouringRequest{}
	mi := &file_v1_touring_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTouringRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTouringRequest) ProtoMessage() {}

func (x *GetTouringRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_touring_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTouringRequest.ProtoReflect.Descriptor instead.
func (*GetTouringRequest) Descriptor() ([]byte, []int) {
	return file_v1_touring_proto_rawDescGZIP(), []int{4}
}

func (x *GetTouringRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetTouringRequest) GetView() TouringView {
	if x != nil {
		return x.View
	}
	return TouringView_TOURING_VIEW_UNSPECIFIED
}

type GetTouringResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Touring       *Touring               `protobuf:"bytes,1,opt,name=touring,proto3" json:"touring,omitempty"`
	IncludedTags  map[string]*Tag        `protobuf:"bytes,2,rep,name=included_tags,json=includedTags,proto3" json:"included_tags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // view=WITH_TAGS時のみ
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTouringResponse) Reset() {
	*x = GetTouringResponse{}
	mi := &file_v1_touring_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTouringResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTouringResponse) ProtoMessage() {}

func (x *GetTouringResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_touring_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTouringResponse.ProtoReflect.Descriptor instead.
func (*GetTouringResponse) Descriptor() ([]byte, []int) {
	return file_v1_touring_proto_rawDescGZIP(), []int{5}
}

func (x *GetTouringResponse) GetTouring() *Touring {
	if x != nil {
		return x.Touring
	}
	return nil
}

func (x *GetTouringResponse) GetIncludedTags() map[string]*Tag {
	if x != nil {
		return x.IncludedTags
	}
	return nil
}

var File_v1_touring_proto protoreflect.FileDescriptor

const file_v1_touring_proto_rawDesc = "" +
	"\n" +
	"\x10v1/touring.proto\x12\x11asaycle.routiq.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x19google/api/resource.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x16google/type/date.proto\x1a\x0ev1/route.proto\x1a\fv1/tag.proto\"\xdf\x03\n" +
	"\aTouring\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x122\n" +
	"\x05route\x18\x02 \x01(\tB\x1c\xfaA\x19\n" +
	"\x17asaycle.routiq.v1.RouteR\x05route\x12\x12\n" +
	"\x04tags\x18\x03 \x03(\tR\x04tags\x12%\n" +
	"\x04date\x18\x04 \x01(\v2\x11.google.type.DateR\x04date\x12!\n" +
	"\fdisplay_name\x18\x05 \x01(\tR\vdisplayName\x12\x12\n" +
	"\x04note\x18\x06 \x01(\tR\x04note\x12\x14\n" +
	"\x05score\x18\a \x01(\x05R\x05score\x124\n" +
	"\auser_id\x18\b \x01(\tB\x1b\xfaA\x18\n" +
	"\x16asaycle.routiq.v1.UserR\x06userId\x12;\n" +
	"\vcreate_time\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"createTime\x12;\n" +
	"\vupdate_time\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"updateTime:T\xeaAQ\n" +
	"\x19asaycle.routiq.v1.Touring\x12!routes/{route}/tourings/{touring}*\btourings2\atouring\"\x82\x01\n" +
	"\x14CreateTouringRequest\x124\n" +
	"\x06parent\x18\x01 \x01(\tB\x1c\xfaA\x19\n" +
	"\x17asaycle.routiq.v1.RouteR\x06parent\x124\n" +
	"\atouring\x18\x02 \x01(\v2\x1a.asaycle.routiq.v1.TouringR\atouring\"\x9d\x01\n" +
	"\x13ListTouringsRequest\x12\x16\n" +
	"\x06filter\x18\x01 \x01(\tR\x06filter\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x03 \x01(\tR\tpageToken\x122\n" +
	"\x04view\x18\x04 \x01(\x0e2\x1e.asaycle.routiq.v1.TouringViewR\x04view\"\xaf\x02\n" +
	"\x14ListTouringsResponse\x126\n" +
	"\btourings\x18\x01 \x03(\v2\x1a.asaycle.routiq.v1.TouringR\btourings\x12^\n" +
	"\rincluded_tags\x18\x02 \x03(\v29.asaycle.routiq.v1.ListTouringsResponse.IncludedTagsEntryR\fincludedTags\x12&\n" +
	"\x0fnext_page_token\x18\x03 \x01(\tR\rnextPageToken\x1aW\n" +
	"\x11IncludedTagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12,\n" +
	"\x05value\x18\x02 \x01(\v2\x16.asaycle.routiq.v1.TagR\x05value:\x028\x01\"[\n" +
	"\x11GetTouringRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x122\n" +
	"\x04view\x18\x02 \x01(\x0e2\x1e.asaycle.routiq.v1.TouringViewR\x04view\"\x81\x02\n" +
	"\x12GetTouringResponse\x124\n" +
	"\atouring\x18\x01 \x01(\v2\x1a.asaycle.routiq.v1.TouringR\atouring\x12\\\n" +
	"\rincluded_tags\x18\x02 \x03(\v27.asaycle.routiq.v1.GetTouringResponse.IncludedTagsEntryR\fincludedTags\x1aW\n" +
	"\x11IncludedTagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12,\n" +
	"\x05value\x18\x02 \x01(\v2\x16.asaycle.routiq.v1.TagR\x05value:\x028\x01*_\n" +
	"\vTouringView\x12\x1c\n" +
	"\x18TOURING_VIEW_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12TOURING_VIEW_BASIC\x10\x01\x12\x1a\n" +
	"\x16TOURING_VIEW_WITH_TAGS\x10\x022\xa2\x02\n" +
	"\x0eTouringService\x12T\n" +
	"\rCreateTouring\x12'.asaycle.routiq.v1.CreateTouringRequest\x1a\x1a.asaycle.routiq.v1.Touring\x12_\n" +
	"\fListTourings\x12&.asaycle.routiq.v1.ListTouringsRequest\x1a'.asaycle.routiq.v1.ListTouringsResponse\x12Y\n" +
	"\n" +
	"GetTouring\x12$.asaycle.routiq.v1.GetTouringRequest\x1a%.asaycle.routiq.v1.GetTouringResponseB/Z-github.com/asaycle/routiq/api/proto/v1;routiqb\x06proto3"

var (
	file_v1_touring_proto_rawDescOnce sync.Once
	file_v1_touring_proto_rawDescData []byte
)

func file_v1_touring_proto_rawDescGZIP() []byte {
	file_v1_touring_proto_rawDescOnce.Do(func() {
		file_v1_touring_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_touring_proto_rawDesc), len(file_v1_touring_proto_rawDesc)))
	})
	return file_v1_touring_proto_rawDescData
}

var file_v1_touring_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_v1_touring_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_v1_touring_proto_goTypes = []any{
	(TouringView)(0),              // 0: asaycle.routiq.v1.TouringView
	(*Touring)(nil),               // 1: asaycle.routiq.v1.Touring
	(*CreateTouringRequest)(nil),  // 2: asaycle.routiq.v1.CreateTouringRequest
	(*ListTouringsRequest)(nil),   // 3: asaycle.routiq.v1.ListTouringsRequest
	(*ListTouringsResponse)(nil),  // 4: asaycle.routiq.v1.ListTouringsResponse
	(*GetTouringRequest)(nil),     // 5: asaycle.routiq.v1.GetTouringRequest
	(*GetTouringResponse)(nil),    // 6: asaycle.routiq.v1.GetTouringResponse
	nil,                           // 7: asaycle.routiq.v1.ListTouringsResponse.IncludedTagsEntry
	nil,                           // 8: asaycle.routiq.v1.GetTouringResponse.IncludedTagsEntry
	(*date.Date)(nil),             // 9: google.type.Date
	(*timestamppb.Timestamp)(nil), // 10: google.protobuf.Timestamp
	(*Tag)(nil),                   // 11: asaycle.routiq.v1.Tag
}
var file_v1_touring_proto_depIdxs = []int32{
	9,  // 0: asaycle.routiq.v1.Touring.date:type_name -> google.type.Date
	10, // 1: asaycle.routiq.v1.Touring.create_time:type_name -> google.protobuf.Timestamp
	10, // 2: asaycle.routiq.v1.Touring.update_time:type_name -> google.protobuf.Timestamp
	1,  // 3: asaycle.routiq.v1.CreateTouringRequest.touring:type_name -> asaycle.routiq.v1.Touring
	0,  // 4: asaycle.routiq.v1.ListTouringsRequest.view:type_name -> asaycle.routiq.v1.TouringView
	1,  // 5: asaycle.routiq.v1.ListTouringsResponse.tourings:type_name -> asaycle.routiq.v1.Touring
	7,  // 6: asaycle.routiq.v1.ListTouringsResponse.included_tags:type_name -> asaycle.routiq.v1.ListTouringsResponse.IncludedTagsEntry
	0,  // 7: asaycle.routiq.v1.GetTouringRequest.view:type_name -> asaycle.routiq.v1.TouringView
	1,  // 8: asaycle.routiq.v1.GetTouringResponse.touring:type_name -> asaycle.routiq.v1.Touring
	8,  // 9: asaycle.routiq.v1.GetTouringResponse.included_tags:type_name -> asaycle.routiq.v1.GetTouringResponse.IncludedTagsEntry
	11, // 10: asaycle.routiq.v1.ListTouringsResponse.IncludedTagsEntry.value:type_name -> asaycle.routiq.v1.Tag
	11, // 11: asaycle.routiq.v1.GetTouringResponse.IncludedTagsEntry.value:type_name -> asaycle.routiq.v1.Tag
	2,  // 12: asaycle.routiq.v1.TouringService.CreateTouring:input_type -> asaycle.routiq.v1.CreateTouringRequest
	3,  // 13: asaycle.routiq.v1.TouringService.ListTourings:input_type -> asaycle.routiq.v1.ListTouringsRequest
	5,  // 14: asaycle.routiq.v1.TouringService.GetTouring:input_type -> asaycle.routiq.v1.GetTouringRequest
	1,  // 15: asaycle.routiq.v1.TouringService.CreateTouring:output_type -> asaycle.routiq.v1.Touring
	4,  // 16: asaycle.routiq.v1.TouringService.ListTourings:output_type -> asaycle.routiq.v1.ListTouringsResponse
	6,  // 17: asaycle.routiq.v1.TouringService.GetTouring:output_type -> asaycle.routiq.v1.GetTouringResponse
	15, // [15:18] is the sub-list for method output_type
	12, // [12:15] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_v1_touring_proto_init() }
func file_v1_touring_proto_init() {
	if File_v1_touring_proto != nil {
		return
	}
	file_v1_route_proto_init()
	file_v1_tag_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_touring_proto_rawDesc), len(file_v1_touring_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_touring_proto_goTypes,
		DependencyIndexes: file_v1_touring_proto_depIdxs,
		EnumInfos:         file_v1_touring_proto_enumTypes,
		MessageInfos:      file_v1_touring_proto_msgTypes,
	}.Build()
	File_v1_touring_proto = out.File
	file_v1_touring_proto_goTypes = nil
	file_v1_touring_proto_depIdxs = nil
}
