// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: v1/touring.proto

package routiq

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	date "google.golang.org/genproto/googleapis/type/date"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Touring リソース定義
type Touring struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // XID型の一意のID
	RouteId       string                 `protobuf:"bytes,2,opt,name=route_id,json=routeId,proto3" json:"route_id,omitempty"`
	Tags          []*Tag                 `protobuf:"bytes,3,rep,name=tags,proto3" json:"tags,omitempty"`
	Date          *date.Date             `protobuf:"bytes,4,opt,name=date,proto3" json:"date,omitempty"`
	Title         string                 `protobuf:"bytes,5,opt,name=title,proto3" json:"title,omitempty"` // ルート名
	Note          string                 `protobuf:"bytes,6,opt,name=note,proto3" json:"note,omitempty"`
	Score         int32                  `protobuf:"varint,7,opt,name=score,proto3" json:"score,omitempty"`
	UserId        string                 `protobuf:"bytes,8,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // 作成日時 (ISO8601形式の文字列)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Touring) Reset() {
	*x = Touring{}
	mi := &file_v1_touring_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Touring) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Touring) ProtoMessage() {}

func (x *Touring) ProtoReflect() protoreflect.Message {
	mi := &file_v1_touring_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Touring.ProtoReflect.Descriptor instead.
func (*Touring) Descriptor() ([]byte, []int) {
	return file_v1_touring_proto_rawDescGZIP(), []int{0}
}

func (x *Touring) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Touring) GetRouteId() string {
	if x != nil {
		return x.RouteId
	}
	return ""
}

func (x *Touring) GetTags() []*Tag {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Touring) GetDate() *date.Date {
	if x != nil {
		return x.Date
	}
	return nil
}

func (x *Touring) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Touring) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

func (x *Touring) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *Touring) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Touring) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

// CreateTouring RPC
type CreateTouringRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Touring       *Touring               `protobuf:"bytes,1,opt,name=touring,proto3" json:"touring,omitempty"` // ライド名
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTouringRequest) Reset() {
	*x = CreateTouringRequest{}
	mi := &file_v1_touring_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTouringRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTouringRequest) ProtoMessage() {}

func (x *CreateTouringRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_touring_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTouringRequest.ProtoReflect.Descriptor instead.
func (*CreateTouringRequest) Descriptor() ([]byte, []int) {
	return file_v1_touring_proto_rawDescGZIP(), []int{1}
}

func (x *CreateTouringRequest) GetTouring() *Touring {
	if x != nil {
		return x.Touring
	}
	return nil
}

// ListTourings RPC
type ListTouringsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filter        string                 `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`   // 一度に取得するルートの数
	PageToken     string                 `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"` // 次のページを指定するトークン
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTouringsRequest) Reset() {
	*x = ListTouringsRequest{}
	mi := &file_v1_touring_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTouringsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTouringsRequest) ProtoMessage() {}

func (x *ListTouringsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_touring_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTouringsRequest.ProtoReflect.Descriptor instead.
func (*ListTouringsRequest) Descriptor() ([]byte, []int) {
	return file_v1_touring_proto_rawDescGZIP(), []int{2}
}

func (x *ListTouringsRequest) GetFilter() string {
	if x != nil {
		return x.Filter
	}
	return ""
}

func (x *ListTouringsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListTouringsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListTouringsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tourings      []*Touring             `protobuf:"bytes,1,rep,name=tourings,proto3" json:"tourings,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"` // 次のページのトークン
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTouringsResponse) Reset() {
	*x = ListTouringsResponse{}
	mi := &file_v1_touring_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTouringsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTouringsResponse) ProtoMessage() {}

func (x *ListTouringsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_touring_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTouringsResponse.ProtoReflect.Descriptor instead.
func (*ListTouringsResponse) Descriptor() ([]byte, []int) {
	return file_v1_touring_proto_rawDescGZIP(), []int{3}
}

func (x *ListTouringsResponse) GetTourings() []*Touring {
	if x != nil {
		return x.Tourings
	}
	return nil
}

func (x *ListTouringsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

// GetTouring RPC
type GetTouringRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // 取得するルートのID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTouringRequest) Reset() {
	*x = GetTouringRequest{}
	mi := &file_v1_touring_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTouringRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTouringRequest) ProtoMessage() {}

func (x *GetTouringRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_touring_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTouringRequest.ProtoReflect.Descriptor instead.
func (*GetTouringRequest) Descriptor() ([]byte, []int) {
	return file_v1_touring_proto_rawDescGZIP(), []int{4}
}

func (x *GetTouringRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_v1_touring_proto protoreflect.FileDescriptor

const file_v1_touring_proto_rawDesc = "" +
	"\n" +
	"\x10v1/touring.proto\x12\x11asaycle.routiq.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x19google/api/resource.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x16google/type/date.proto\x1a\x0ev1/route.proto\x1a\fv1/tag.proto\"\xf1\x02\n" +
	"\aTouring\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\broute_id\x18\x02 \x01(\tR\arouteId\x12*\n" +
	"\x04tags\x18\x03 \x03(\v2\x16.asaycle.routiq.v1.TagR\x04tags\x12%\n" +
	"\x04date\x18\x04 \x01(\v2\x11.google.type.DateR\x04date\x12\x14\n" +
	"\x05title\x18\x05 \x01(\tR\x05title\x12\x12\n" +
	"\x04note\x18\x06 \x01(\tR\x04note\x12\x14\n" +
	"\x05score\x18\a \x01(\x05R\x05score\x12\x17\n" +
	"\auser_id\x18\b \x01(\tR\x06userId\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt:T\xeaAQ\n" +
	"\x19asaycle.routiq.v1.Touring\x12!routes/{route}/tourings/{touring}*\btourings2\atouring\"L\n" +
	"\x14CreateTouringRequest\x124\n" +
	"\atouring\x18\x01 \x01(\v2\x1a.asaycle.routiq.v1.TouringR\atouring\"i\n" +
	"\x13ListTouringsRequest\x12\x16\n" +
	"\x06filter\x18\x01 \x01(\tR\x06filter\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x03 \x01(\tR\tpageToken\"v\n" +
	"\x14ListTouringsResponse\x126\n" +
	"\btourings\x18\x01 \x03(\v2\x1a.asaycle.routiq.v1.TouringR\btourings\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"#\n" +
	"\x11GetTouringRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id2\x97\x02\n" +
	"\x0eTouringService\x12T\n" +
	"\rCreateTouring\x12'.asaycle.routiq.v1.CreateTouringRequest\x1a\x1a.asaycle.routiq.v1.Touring\x12_\n" +
	"\fListTourings\x12&.asaycle.routiq.v1.ListTouringsRequest\x1a'.asaycle.routiq.v1.ListTouringsResponse\x12N\n" +
	"\n" +
	"GetTouring\x12$.asaycle.routiq.v1.GetTouringRequest\x1a\x1a.asaycle.routiq.v1.TouringB/Z-github.com/asaycle/routiq/api/proto/v1;routiqb\x06proto3"

var (
	file_v1_touring_proto_rawDescOnce sync.Once
	file_v1_touring_proto_rawDescData []byte
)

func file_v1_touring_proto_rawDescGZIP() []byte {
	file_v1_touring_proto_rawDescOnce.Do(func() {
		file_v1_touring_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_touring_proto_rawDesc), len(file_v1_touring_proto_rawDesc)))
	})
	return file_v1_touring_proto_rawDescData
}

var file_v1_touring_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_v1_touring_proto_goTypes = []any{
	(*Touring)(nil),               // 0: asaycle.routiq.v1.Touring
	(*CreateTouringRequest)(nil),  // 1: asaycle.routiq.v1.CreateTouringRequest
	(*ListTouringsRequest)(nil),   // 2: asaycle.routiq.v1.ListTouringsRequest
	(*ListTouringsResponse)(nil),  // 3: asaycle.routiq.v1.ListTouringsResponse
	(*GetTouringRequest)(nil),     // 4: asaycle.routiq.v1.GetTouringRequest
	(*Tag)(nil),                   // 5: asaycle.routiq.v1.Tag
	(*date.Date)(nil),             // 6: google.type.Date
	(*timestamppb.Timestamp)(nil), // 7: google.protobuf.Timestamp
}
var file_v1_touring_proto_depIdxs = []int32{
	5, // 0: asaycle.routiq.v1.Touring.tags:type_name -> asaycle.routiq.v1.Tag
	6, // 1: asaycle.routiq.v1.Touring.date:type_name -> google.type.Date
	7, // 2: asaycle.routiq.v1.Touring.created_at:type_name -> google.protobuf.Timestamp
	0, // 3: asaycle.routiq.v1.CreateTouringRequest.touring:type_name -> asaycle.routiq.v1.Touring
	0, // 4: asaycle.routiq.v1.ListTouringsResponse.tourings:type_name -> asaycle.routiq.v1.Touring
	1, // 5: asaycle.routiq.v1.TouringService.CreateTouring:input_type -> asaycle.routiq.v1.CreateTouringRequest
	2, // 6: asaycle.routiq.v1.TouringService.ListTourings:input_type -> asaycle.routiq.v1.ListTouringsRequest
	4, // 7: asaycle.routiq.v1.TouringService.GetTouring:input_type -> asaycle.routiq.v1.GetTouringRequest
	0, // 8: asaycle.routiq.v1.TouringService.CreateTouring:output_type -> asaycle.routiq.v1.Touring
	3, // 9: asaycle.routiq.v1.TouringService.ListTourings:output_type -> asaycle.routiq.v1.ListTouringsResponse
	0, // 10: asaycle.routiq.v1.TouringService.GetTouring:output_type -> asaycle.routiq.v1.Touring
	8, // [8:11] is the sub-list for method output_type
	5, // [5:8] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_v1_touring_proto_init() }
func file_v1_touring_proto_init() {
	if File_v1_touring_proto != nil {
		return
	}
	file_v1_route_proto_init()
	file_v1_tag_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_touring_proto_rawDesc), len(file_v1_touring_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_touring_proto_goTypes,
		DependencyIndexes: file_v1_touring_proto_depIdxs,
		MessageInfos:      file_v1_touring_proto_msgTypes,
	}.Build()
	File_v1_touring_proto = out.File
	file_v1_touring_proto_goTypes = nil
	file_v1_touring_proto_depIdxs = nil
}
