// Code generated by protoc-gen-go-resourcename; DO NOT EDIT.
package routiq

// User patterns
type UserNameVariant int

const (
	UserNameVariant0 UserNameVariant = 0 // users/{user}
)

var _UserVariants = [][]_pattern{
	{_pattern{_seg{_segLit, "users"}, _seg{_segVar, "user"}}},
}

type UserName struct {
	Variant UserNameVariant
	user    string
}

func ParseUserName(name string) (UserName, error) {
	vars, which, err := _parseByVariants(name, _UserVariants)
	if err != nil {
		return UserName{}, err
	}
	out := UserName{Variant: UserNameVariant(which)}
	out.user = vars["user"]
	return out, nil
}

func FormatUserName(user string) string {
	return "users" + "/" + user
}

func (n UserName) GetUser() string { return n.user }
