/**
 * @fileoverview gRPC-Web generated client stub for asaycle.routiq.v1
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v3.19.1
// source: v1/announcement.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as v1_announcement_pb from '../v1/announcement_pb'; // proto import: "v1/announcement.proto"


export class AnnouncementServiceClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorListAnnouncements = new grpcWeb.MethodDescriptor(
    '/asaycle.routiq.v1.AnnouncementService/ListAnnouncements',
    grpcWeb.MethodType.UNARY,
    v1_announcement_pb.ListAnnouncementsRequest,
    v1_announcement_pb.ListAnnouncementsResponse,
    (request: v1_announcement_pb.ListAnnouncementsRequest) => {
      return request.serializeBinary();
    },
    v1_announcement_pb.ListAnnouncementsResponse.deserializeBinary
  );

  listAnnouncements(
    request: v1_announcement_pb.ListAnnouncementsRequest,
    metadata?: grpcWeb.Metadata | null): Promise<v1_announcement_pb.ListAnnouncementsResponse>;

  listAnnouncements(
    request: v1_announcement_pb.ListAnnouncementsRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: v1_announcement_pb.ListAnnouncementsResponse) => void): grpcWeb.ClientReadableStream<v1_announcement_pb.ListAnnouncementsResponse>;

  listAnnouncements(
    request: v1_announcement_pb.ListAnnouncementsRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: v1_announcement_pb.ListAnnouncementsResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/asaycle.routiq.v1.AnnouncementService/ListAnnouncements',
        request,
        metadata || {},
        this.methodDescriptorListAnnouncements,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/asaycle.routiq.v1.AnnouncementService/ListAnnouncements',
    request,
    metadata || {},
    this.methodDescriptorListAnnouncements);
  }

  methodDescriptorGetAnnouncement = new grpcWeb.MethodDescriptor(
    '/asaycle.routiq.v1.AnnouncementService/GetAnnouncement',
    grpcWeb.MethodType.UNARY,
    v1_announcement_pb.GetAnnouncementRequest,
    v1_announcement_pb.Announcement,
    (request: v1_announcement_pb.GetAnnouncementRequest) => {
      return request.serializeBinary();
    },
    v1_announcement_pb.Announcement.deserializeBinary
  );

  getAnnouncement(
    request: v1_announcement_pb.GetAnnouncementRequest,
    metadata?: grpcWeb.Metadata | null): Promise<v1_announcement_pb.Announcement>;

  getAnnouncement(
    request: v1_announcement_pb.GetAnnouncementRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: v1_announcement_pb.Announcement) => void): grpcWeb.ClientReadableStream<v1_announcement_pb.Announcement>;

  getAnnouncement(
    request: v1_announcement_pb.GetAnnouncementRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: v1_announcement_pb.Announcement) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/asaycle.routiq.v1.AnnouncementService/GetAnnouncement',
        request,
        metadata || {},
        this.methodDescriptorGetAnnouncement,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/asaycle.routiq.v1.AnnouncementService/GetAnnouncement',
    request,
    metadata || {},
    this.methodDescriptorGetAnnouncement);
  }

}

