/**
 * @fileoverview gRPC-Web generated client stub for asaycle.routiq.v1
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v3.19.1
// source: v1/auth.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as v1_auth_pb from '../v1/auth_pb'; // proto import: "v1/auth.proto"


export class AuthServiceClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorExchangeOAuthCode = new grpcWeb.MethodDescriptor(
    '/asaycle.routiq.v1.AuthService/ExchangeOAuthCode',
    grpcWeb.MethodType.UNARY,
    v1_auth_pb.ExchangeOAuthCodeRequest,
    v1_auth_pb.ExchangeOAuthCodeResponse,
    (request: v1_auth_pb.ExchangeOAuthCodeRequest) => {
      return request.serializeBinary();
    },
    v1_auth_pb.ExchangeOAuthCodeResponse.deserializeBinary
  );

  exchangeOAuthCode(
    request: v1_auth_pb.ExchangeOAuthCodeRequest,
    metadata?: grpcWeb.Metadata | null): Promise<v1_auth_pb.ExchangeOAuthCodeResponse>;

  exchangeOAuthCode(
    request: v1_auth_pb.ExchangeOAuthCodeRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: v1_auth_pb.ExchangeOAuthCodeResponse) => void): grpcWeb.ClientReadableStream<v1_auth_pb.ExchangeOAuthCodeResponse>;

  exchangeOAuthCode(
    request: v1_auth_pb.ExchangeOAuthCodeRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: v1_auth_pb.ExchangeOAuthCodeResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/asaycle.routiq.v1.AuthService/ExchangeOAuthCode',
        request,
        metadata || {},
        this.methodDescriptorExchangeOAuthCode,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/asaycle.routiq.v1.AuthService/ExchangeOAuthCode',
    request,
    metadata || {},
    this.methodDescriptorExchangeOAuthCode);
  }

  methodDescriptorRefreshToken = new grpcWeb.MethodDescriptor(
    '/asaycle.routiq.v1.AuthService/RefreshToken',
    grpcWeb.MethodType.UNARY,
    v1_auth_pb.RefreshTokenRequest,
    v1_auth_pb.RefreshTokenResponse,
    (request: v1_auth_pb.RefreshTokenRequest) => {
      return request.serializeBinary();
    },
    v1_auth_pb.RefreshTokenResponse.deserializeBinary
  );

  refreshToken(
    request: v1_auth_pb.RefreshTokenRequest,
    metadata?: grpcWeb.Metadata | null): Promise<v1_auth_pb.RefreshTokenResponse>;

  refreshToken(
    request: v1_auth_pb.RefreshTokenRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: v1_auth_pb.RefreshTokenResponse) => void): grpcWeb.ClientReadableStream<v1_auth_pb.RefreshTokenResponse>;

  refreshToken(
    request: v1_auth_pb.RefreshTokenRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: v1_auth_pb.RefreshTokenResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/asaycle.routiq.v1.AuthService/RefreshToken',
        request,
        metadata || {},
        this.methodDescriptorRefreshToken,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/asaycle.routiq.v1.AuthService/RefreshToken',
    request,
    metadata || {},
    this.methodDescriptorRefreshToken);
  }

  methodDescriptorVerifyToken = new grpcWeb.MethodDescriptor(
    '/asaycle.routiq.v1.AuthService/VerifyToken',
    grpcWeb.MethodType.UNARY,
    v1_auth_pb.VerifyTokenRequest,
    v1_auth_pb.VerifyTokenResponse,
    (request: v1_auth_pb.VerifyTokenRequest) => {
      return request.serializeBinary();
    },
    v1_auth_pb.VerifyTokenResponse.deserializeBinary
  );

  verifyToken(
    request: v1_auth_pb.VerifyTokenRequest,
    metadata?: grpcWeb.Metadata | null): Promise<v1_auth_pb.VerifyTokenResponse>;

  verifyToken(
    request: v1_auth_pb.VerifyTokenRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: v1_auth_pb.VerifyTokenResponse) => void): grpcWeb.ClientReadableStream<v1_auth_pb.VerifyTokenResponse>;

  verifyToken(
    request: v1_auth_pb.VerifyTokenRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: v1_auth_pb.VerifyTokenResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/asaycle.routiq.v1.AuthService/VerifyToken',
        request,
        metadata || {},
        this.methodDescriptorVerifyToken,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/asaycle.routiq.v1.AuthService/VerifyToken',
    request,
    metadata || {},
    this.methodDescriptorVerifyToken);
  }

}

