/**
 * @fileoverview gRPC-Web generated client stub for asaycle.routiq.v1
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v3.19.1
// source: v1/pref.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as v1_pref_pb from '../v1/pref_pb'; // proto import: "v1/pref.proto"


export class PrefServiceClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorListPrefs = new grpcWeb.MethodDescriptor(
    '/asaycle.routiq.v1.PrefService/ListPrefs',
    grpcWeb.MethodType.UNARY,
    v1_pref_pb.ListPrefsRequest,
    v1_pref_pb.ListPrefsResponse,
    (request: v1_pref_pb.ListPrefsRequest) => {
      return request.serializeBinary();
    },
    v1_pref_pb.ListPrefsResponse.deserializeBinary
  );

  listPrefs(
    request: v1_pref_pb.ListPrefsRequest,
    metadata?: grpcWeb.Metadata | null): Promise<v1_pref_pb.ListPrefsResponse>;

  listPrefs(
    request: v1_pref_pb.ListPrefsRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: v1_pref_pb.ListPrefsResponse) => void): grpcWeb.ClientReadableStream<v1_pref_pb.ListPrefsResponse>;

  listPrefs(
    request: v1_pref_pb.ListPrefsRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: v1_pref_pb.ListPrefsResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/asaycle.routiq.v1.PrefService/ListPrefs',
        request,
        metadata || {},
        this.methodDescriptorListPrefs,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/asaycle.routiq.v1.PrefService/ListPrefs',
    request,
    metadata || {},
    this.methodDescriptorListPrefs);
  }

}

