/**
 * @fileoverview gRPC-Web generated client stub for asaycle.routiq.v1
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v3.19.1
// source: v1/riding.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as v1_riding_pb from '../v1/riding_pb'; // proto import: "v1/riding.proto"


export class RidingServiceClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorCreateRiding = new grpcWeb.MethodDescriptor(
    '/asaycle.routiq.v1.RidingService/CreateRiding',
    grpcWeb.MethodType.UNARY,
    v1_riding_pb.CreateRidingRequest,
    v1_riding_pb.Riding,
    (request: v1_riding_pb.CreateRidingRequest) => {
      return request.serializeBinary();
    },
    v1_riding_pb.Riding.deserializeBinary
  );

  createRiding(
    request: v1_riding_pb.CreateRidingRequest,
    metadata?: grpcWeb.Metadata | null): Promise<v1_riding_pb.Riding>;

  createRiding(
    request: v1_riding_pb.CreateRidingRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: v1_riding_pb.Riding) => void): grpcWeb.ClientReadableStream<v1_riding_pb.Riding>;

  createRiding(
    request: v1_riding_pb.CreateRidingRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: v1_riding_pb.Riding) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/asaycle.routiq.v1.RidingService/CreateRiding',
        request,
        metadata || {},
        this.methodDescriptorCreateRiding,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/asaycle.routiq.v1.RidingService/CreateRiding',
    request,
    metadata || {},
    this.methodDescriptorCreateRiding);
  }

  methodDescriptorListRidings = new grpcWeb.MethodDescriptor(
    '/asaycle.routiq.v1.RidingService/ListRidings',
    grpcWeb.MethodType.UNARY,
    v1_riding_pb.ListRidingsRequest,
    v1_riding_pb.ListRidingsResponse,
    (request: v1_riding_pb.ListRidingsRequest) => {
      return request.serializeBinary();
    },
    v1_riding_pb.ListRidingsResponse.deserializeBinary
  );

  listRidings(
    request: v1_riding_pb.ListRidingsRequest,
    metadata?: grpcWeb.Metadata | null): Promise<v1_riding_pb.ListRidingsResponse>;

  listRidings(
    request: v1_riding_pb.ListRidingsRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: v1_riding_pb.ListRidingsResponse) => void): grpcWeb.ClientReadableStream<v1_riding_pb.ListRidingsResponse>;

  listRidings(
    request: v1_riding_pb.ListRidingsRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: v1_riding_pb.ListRidingsResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/asaycle.routiq.v1.RidingService/ListRidings',
        request,
        metadata || {},
        this.methodDescriptorListRidings,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/asaycle.routiq.v1.RidingService/ListRidings',
    request,
    metadata || {},
    this.methodDescriptorListRidings);
  }

  methodDescriptorGetRiding = new grpcWeb.MethodDescriptor(
    '/asaycle.routiq.v1.RidingService/GetRiding',
    grpcWeb.MethodType.UNARY,
    v1_riding_pb.GetRidingRequest,
    v1_riding_pb.Riding,
    (request: v1_riding_pb.GetRidingRequest) => {
      return request.serializeBinary();
    },
    v1_riding_pb.Riding.deserializeBinary
  );

  getRiding(
    request: v1_riding_pb.GetRidingRequest,
    metadata?: grpcWeb.Metadata | null): Promise<v1_riding_pb.Riding>;

  getRiding(
    request: v1_riding_pb.GetRidingRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: v1_riding_pb.Riding) => void): grpcWeb.ClientReadableStream<v1_riding_pb.Riding>;

  getRiding(
    request: v1_riding_pb.GetRidingRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: v1_riding_pb.Riding) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/asaycle.routiq.v1.RidingService/GetRiding',
        request,
        metadata || {},
        this.methodDescriptorGetRiding,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/asaycle.routiq.v1.RidingService/GetRiding',
    request,
    metadata || {},
    this.methodDescriptorGetRiding);
  }

}

