/**
 * @fileoverview gRPC-Web generated client stub for asaycle.routiq.v1
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v3.19.1
// source: v1/touring.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as v1_touring_pb from '../v1/touring_pb'; // proto import: "v1/touring.proto"


export class TouringServiceClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorCreateTouring = new grpcWeb.MethodDescriptor(
    '/asaycle.routiq.v1.TouringService/CreateTouring',
    grpcWeb.MethodType.UNARY,
    v1_touring_pb.CreateTouringRequest,
    v1_touring_pb.Touring,
    (request: v1_touring_pb.CreateTouringRequest) => {
      return request.serializeBinary();
    },
    v1_touring_pb.Touring.deserializeBinary
  );

  createTouring(
    request: v1_touring_pb.CreateTouringRequest,
    metadata?: grpcWeb.Metadata | null): Promise<v1_touring_pb.Touring>;

  createTouring(
    request: v1_touring_pb.CreateTouringRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: v1_touring_pb.Touring) => void): grpcWeb.ClientReadableStream<v1_touring_pb.Touring>;

  createTouring(
    request: v1_touring_pb.CreateTouringRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: v1_touring_pb.Touring) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/asaycle.routiq.v1.TouringService/CreateTouring',
        request,
        metadata || {},
        this.methodDescriptorCreateTouring,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/asaycle.routiq.v1.TouringService/CreateTouring',
    request,
    metadata || {},
    this.methodDescriptorCreateTouring);
  }

  methodDescriptorListTourings = new grpcWeb.MethodDescriptor(
    '/asaycle.routiq.v1.TouringService/ListTourings',
    grpcWeb.MethodType.UNARY,
    v1_touring_pb.ListTouringsRequest,
    v1_touring_pb.ListTouringsResponse,
    (request: v1_touring_pb.ListTouringsRequest) => {
      return request.serializeBinary();
    },
    v1_touring_pb.ListTouringsResponse.deserializeBinary
  );

  listTourings(
    request: v1_touring_pb.ListTouringsRequest,
    metadata?: grpcWeb.Metadata | null): Promise<v1_touring_pb.ListTouringsResponse>;

  listTourings(
    request: v1_touring_pb.ListTouringsRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: v1_touring_pb.ListTouringsResponse) => void): grpcWeb.ClientReadableStream<v1_touring_pb.ListTouringsResponse>;

  listTourings(
    request: v1_touring_pb.ListTouringsRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: v1_touring_pb.ListTouringsResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/asaycle.routiq.v1.TouringService/ListTourings',
        request,
        metadata || {},
        this.methodDescriptorListTourings,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/asaycle.routiq.v1.TouringService/ListTourings',
    request,
    metadata || {},
    this.methodDescriptorListTourings);
  }

  methodDescriptorGetTouring = new grpcWeb.MethodDescriptor(
    '/asaycle.routiq.v1.TouringService/GetTouring',
    grpcWeb.MethodType.UNARY,
    v1_touring_pb.GetTouringRequest,
    v1_touring_pb.Touring,
    (request: v1_touring_pb.GetTouringRequest) => {
      return request.serializeBinary();
    },
    v1_touring_pb.Touring.deserializeBinary
  );

  getTouring(
    request: v1_touring_pb.GetTouringRequest,
    metadata?: grpcWeb.Metadata | null): Promise<v1_touring_pb.Touring>;

  getTouring(
    request: v1_touring_pb.GetTouringRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: v1_touring_pb.Touring) => void): grpcWeb.ClientReadableStream<v1_touring_pb.Touring>;

  getTouring(
    request: v1_touring_pb.GetTouringRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: v1_touring_pb.Touring) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/asaycle.routiq.v1.TouringService/GetTouring',
        request,
        metadata || {},
        this.methodDescriptorGetTouring,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/asaycle.routiq.v1.TouringService/GetTouring',
    request,
    metadata || {},
    this.methodDescriptorGetTouring);
  }

}

