name: Deploy to Staging

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Build and Deploy to Staging (Sakura VPS)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker images
        run: |
          docker compose -f docker-compose.yml build

      - name: Save Docker images to archive
        run: |
          docker save routiq-backend routiq-frontend pgdb | gzip > routiq-images.tar.gz

      - name: Upload images to VPS (SCP)
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          source: "routiq-images.tar.gz"
          target: "/home/ubuntu/"

      - name: Remote deploy on VPS (SSH)
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /home/ubuntu
            gunzip -f routiq-images.tar.gz
            sudo docker load < routiq-images.tar
            sudo docker compose -f docker-compose.yml up -d
